### ISSUE TITLE
URI::Data is a URI::Generic

### ISSUE THREAD

**Issue by dblock** [dball/data_uri#6]
I think it would be nice if just like URI::HTTP, URI::Data wasn't of a URI::Generic type. Right now you get:

``` ruby
url = "data:text/html;base64,#{Base64.encode64('<script>alert(location.hash);</script>')}"
> URI.parse(url).is_a?(URI::HTTP)
=> false
> URI.parse(url).is_a?(URI::Data)
=> true
> URI.parse(url).is_a?(URI::Generic)
=> true # this should be false
```

**Comment by dball** [comment]
I'd be happy to accept such a change.

Note that URI.parse, at least as of ruby 1.8, was limited to something like 92 chars by its generic regex, with no apparent ability to register type-specific parsers. Perhaps that's changed in subsequent versions? (Indeed, a motivated contributor might be well-served to submit data-uri support to ruby's stdlib. I, alas, lack such motivation.)

**Comment by dblock** [comment]
I wrong wrong about URI:HTTP, its instances are also URI::Generic, problem between the computer and the chair.
